services:
  - type: worker
    name: blockchain-event-monitor
    runtime: node
    buildCommand: npm install -g pnpm && pnpm install && pnpm run build
    startCommand: node dist/index.js
    plan: starter
    # Use Render auto-scaling to handle spikes
    autoscaling:
      min: 1
      max: 1
    envVars:
      - key: NODE_ENV
        value: production
      - key: WSS_RPC_ENDPOINT
        sync: false
      - key: CONTRACT_ADDRESS
        value: 0x25347B4f8449cCCDEEB52912c0d0d3a1613C98E4
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: POLL_INTERVAL
        value: 15000
      - key: MAX_BLOCKS_PER_BATCH
        value: 10000
      - key: STARTING_BLOCK
        value: latest
